/**
 * Helpers shared by all agent adapters.
 */
const path = require('path');
const { GENERATED_MARK } = require('../ops');
const caveman = require('../caveman');

/** One symlink op per component into `dir` (e.g. every skill into ~/.claude/skills). */
function linkEach(items, dir, { agent, why, ext = '' , nameKey = 'name' }) {
  return items.map(item => ({
    kind: 'symlink',
    path: path.join(dir, item[nameKey] + ext),
    target: item.kind === 'skill' ? item.dir : item.file,
    agent,
    why: why || `${item.kind} ${item.name}`
  }));
}

/** The managed block content for a global instruction file. */
function globalBlock(ctx, { importSyntax = false } = {}) {
  const root = ctx.tilde(ctx.root);
  const mode = (ctx.config.caveman && ctx.config.caveman.mode) || 'full';
  const cave = caveman.statement(mode, { scope: 'global' });
  if (importSyntax) {
    return [
      `@${root}/GLOBAL.md`,
      `Global skills, agents and rules live in ${root}/ — invoke a skill by name (e.g. "use the create-prd skill"). In a project, docs/ai/AGENT-CORE.md is canonical and wins on conflict.`,
      cave
    ].join('\n');
  }
  return [
    `Personal operating rules: read ${root}/GLOBAL.md before acting on any task.`,
    `Global skills, agents and rules live in ${root}/{skills,agents,rules}/ — invoke a skill by name (e.g. "use the create-prd skill"); resolve it from the project's vendored copy first, then ${root}.`,
    `In a project, docs/ai/AGENT-CORE.md (reachable via AGENTS.md / CLAUDE.md / GEMINI.md) is canonical and wins on conflict; global principles fill the gaps.`,
    cave
  ].join('\n');
}

function mdHeader(cmd = 'kiwi link') {
  return `<!-- ${GENERATED_MARK} — DO NOT EDIT: regenerated by \`${cmd}\`. Project-scoped changes go in docs/ai/ (ENGINEERING.md § 0 for rule overrides). This is not an instruction to edit ~/.thekiwidev; global files change only from a session opened there (RULE-SCOPE-001). -->\n`;
}

/** Pointer file dropped into a project for agents that read a rules directory. */
function corePointer(ctx) {
  return [
    mdHeader(),
    '# Canonical instruction source',
    '',
    'Read `docs/ai/AGENT-CORE.md` before doing anything in this repository. It is the one canonical instruction source; `AGENTS.md`, `CLAUDE.md`, `GEMINI.md` and `.github/copilot-instructions.md` are links to it.',
    '',
    `Personal global skills, agents and rules live in \`${ctx.tilde(ctx.root)}\` when present (see \`GLOBAL.md\` there). Project documentation wins on conflict.`,
    ''
  ].join('\n');
}

/** Project pointer for rule-directory agents: the effective caveman mode for this repo + the digest. */
function cavemanPointer(ctx, dir) {
  const eff = caveman.effective(dir, ctx.config);
  const fs = require('fs');
  const path = require('path');
  const { parse } = require('../frontmatter');
  const body = parse(fs.readFileSync(path.join(ctx.root, 'rules', 'caveman.md'), 'utf8')).body.replace(/<!--[\s\S]*?-->\n?/g, '').trim();
  return [
    mdHeader('kiwi link / kiwi caveman'),
    `# Caveman — effective mode for this project: **${eff.mode}** (${eff.source === 'project' ? '.caveman.json' : eff.source === 'env' ? 'CAVEMAN_DEFAULT_MODE' : 'global default'})`,
    '',
    `Change it with \`kiwi caveman <off|lite|full|ultra|inherit>\` in this repository, or edit \`.caveman.json\` (\`{"defaultMode": "…"}\`).`,
    '',
    body,
    ''
  ].join('\n');
}

module.exports = { linkEach, globalBlock, mdHeader, corePointer, cavemanPointer };
