const path = require('path');
const { linkEach, globalBlock } = require('./common');
const { GENERATED_MARK } = require('../ops');

const id = 'gemini';
const name = 'Gemini CLI';

function wrapper(ctx, skill) {
  const esc = s => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return [
    `# ${GENERATED_MARK} — DO NOT EDIT: regenerated by \`kiwi install\` from the ${skill.name} skill's frontmatter`,
    `description = "${esc(skill.description)}"`,
    'prompt = """',
    `Activate the \`${skill.name}\` skill (~/.gemini/skills/${skill.name}/SKILL.md) and follow it completely.`,
    '',
    'Task: {{args}}',
    '"""',
    ''
  ].join('\n');
}

function global(ctx) {
  const ops = [
    ...linkEach(ctx.registry.skills, path.join(ctx.homes.gemini, 'skills'), { agent: id }),
    { kind: 'managed', path: path.join(ctx.homes.gemini, 'GEMINI.md'), inner: globalBlock(ctx), agent: id, why: 'global GEMINI.md → GLOBAL.md (shared with Antigravity)' }
  ];
  if (ctx.config.wrappers.gemini) {
    for (const s of ctx.registry.skills.filter(s => s.invocable)) {
      ops.push({ kind: 'file', path: path.join(ctx.homes.gemini, 'commands', `${s.name}.toml`), content: wrapper(ctx, s), agent: id, why: `/${s.name}` });
    }
  }
  return ops;
}

function project(ctx, dir) {
  return [{ kind: 'symlink', path: path.join(dir, 'GEMINI.md'), target: 'docs/ai/AGENT-CORE.md', agent: id, why: 'entry point' }];
}

module.exports = { id, name, global, project, wrapper };
